#!/usr/bin/env python3
"""Regenerate the SHARDED memory index, preserving curated one-liner descriptions.

Writes one `_index-<folder>.md` per folder (full note list) + a THIN MEMORY.md
(domain-grouped table of contents linking to the shards, with counts). This keeps
MEMORY.md tiny (grows with folders, not notes) so it never hits the harness read cap;
the SessionStart hook cats the shards so the full list still loads.

Descriptions are preserved from the existing `_index-*.md` shards, else the old flat
MEMORY.md (migration), else the note's `description:` frontmatter.
Default = dry-run. Pass --write to apply."""

import os, re, glob, sys, shutil

# find _hooklib whether installed (~/.claude/hooks) or bundled in a plugin (../../../hooks)
_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.expanduser("~/.claude/hooks"))
sys.path.insert(0, os.path.join(_here, "..", "..", "..", "hooks"))
import _hooklib as HL

MEM = HL.MEM
WRITE = "--write" in sys.argv

# Auto-generated / journal dirs that never get a note index.
RESERVED = {"Daily", "Weekly", "Sessions", "_system"}
DEFAULT_DOMAIN = ("notes", "🗂️ Notes")

# folder -> (domain, human title), from config.json "domains". Any folder found on
# disk but not listed here is auto-discovered and filed under the default domain.
FOLDERS = {k: tuple(v) for k, v in HL.CONFIG.get("domains", {}).items()}
# ordered (domain, section-heading) pairs for the thin TOC, from config "domain_order".
# Domains present but unlisted are appended automatically.
DOMAIN_ORDER = [tuple(x) for x in HL.CONFIG.get("domain_order", [])]


def field(p, k):
    t = open(p, errors="ignore").read()[:800]
    m = re.search(rf"^{k}:\s*(.+)$", t, re.M)
    return m.group(1).strip().strip("\"'") if m else ""


def load_tails():
    """name -> ' — desc' from existing _index-*.md shards, then old flat MEMORY.md."""
    tails = {}
    srcs = sorted(glob.glob(os.path.join(MEM, "_index-*.md")))
    srcs.append(os.path.join(MEM, "MEMORY.md"))
    for src in srcs:
        if not os.path.exists(src):
            continue
        for ln in open(src, errors="ignore"):
            m = re.match(r"-\s*\[\[([^\]|]+)(?:\|[^\]]+)?\]\](.*)$", ln.strip())
            if m and m.group(1) not in tails and m.group(2).strip():
                tails[m.group(1)] = m.group(2)
    return tails


def main():
    tails = load_tails()
    sections = {}  # folder -> list of (last_confirmed, line)
    for p in glob.glob(os.path.join(MEM, "*", "*.md")):
        b = os.path.splitext(os.path.basename(p))[0]
        if b.startswith("_"):
            continue
        folder = os.path.basename(os.path.dirname(p))
        if folder in RESERVED or folder.startswith("."):
            continue
        if folder not in FOLDERS:  # auto-discover folders not in config
            FOLDERS[folder] = (DEFAULT_DOMAIN[0], folder)
        tail = tails.get(b) or (
            f" — {field(p, 'description')[:120]}" if field(p, "description") else ""
        )
        lc = field(p, "last_confirmed") or "0000-00-00"
        sections.setdefault(folder, []).append((lc, f"- [[{b}]]{tail}"))

    # --- per-folder shard files ---
    shard_files, total = [], 0
    for folder, (domain, title) in FOLDERS.items():
        rows = sections.get(folder)
        if not rows:
            continue
        lines = [ln for _, ln in sorted(rows, reverse=True)]
        total += len(lines)
        body = (
            [
                "---",
                f"tags: [{domain}, project/{folder}, type/moc]",
                f"name: index-{folder}",
                f'title: "Index — {title}"',
                f'description: "Auto-generated note index for the {folder}/ folder ({len(lines)} notes)."',
                "status: active",
                "---",
                "",
                f"# Index — {title}",
                "",
                f"Auto-generated by `/second-brain regen-index.py`. {len(lines)} notes. ↩ [[MEMORY]] · [[_Home]]",
                "",
            ]
            + lines
            + [""]
        )
        shard = os.path.join(MEM, f"_index-{folder}.md")
        shard_files.append((shard, "\n".join(body)))

    # --- thin MEMORY.md (domain-grouped TOC) ---
    out = [
        "# MEMORY — index of Claude memory notes",
        "",
        "Thin table of contents. Each folder's full note list lives in its `[[_index-<folder>]]` shard "
        "(auto-loaded at session start). Regenerated by `/second-brain` (regen-index.py). "
        "`MEMORY.md`, `context.md`, `_session-log.md` stay at root.",
        "",
    ]
    # config order first, then any domain present but unlisted (incl. auto-discovered).
    order = list(DOMAIN_ORDER)
    known = {d for d, _ in order}
    for d, _t in FOLDERS.values():
        if d not in known:
            order.append(DEFAULT_DOMAIN if d == DEFAULT_DOMAIN[0] else (d, d))
            known.add(d)
    for domain, dtitle in order:
        fs = [
            (f, t) for f, (d, t) in FOLDERS.items() if d == domain and sections.get(f)
        ]
        if not fs:
            continue
        out.append(f"## {dtitle}")
        for f, t in fs:
            out.append(f"- [[_index-{f}]] — {t} ({len(sections[f])})")
        out.append("")
    mem_txt = "\n".join(out).rstrip() + "\n"

    if not WRITE:
        print(
            f"[dry-run] {total} notes across {len(shard_files)} shards; "
            f"MEMORY.md would be {len(mem_txt.encode())} bytes. Pass --write."
        )
        return
    mem_md = os.path.join(MEM, "MEMORY.md")
    if os.path.exists(mem_md):
        shutil.copy2(mem_md, mem_md + ".bak")
    for path, text in shard_files:
        HL.atomic_write(path, text)
    HL.atomic_write(mem_md, mem_txt)
    print(
        f"WROTE {len(shard_files)} shards + thin MEMORY.md ({len(mem_txt.encode())} bytes, "
        f"{total} notes). backup: MEMORY.md.bak"
    )


if __name__ == "__main__":
    main()
