#!/usr/bin/env python3
"""Stop hook: append a one-line capture of the finished exchange to today's daily note.
Distilled from a <!--CAPTURE: ...--> footer if present, else a raw fallback from the user msg.
Reads only the TAIL of the (possibly 20MB+) transcript. Never blocks; logs failures."""

import sys, os, json, re
from datetime import datetime

import _hooklib as HL


def _write_last_session(now, proj, branch, last_user, last_asst):
    """Overwrite _infra/_last-session.md with a distilled resume digest of this exchange."""
    try:
        ctx = (proj + (f"@{branch}" if branch else "")) if proj else "(no project)"
        asked = re.sub(r"\s+", " ", last_user or "").strip()
        did = re.sub(r"<!--\s*CAPTURE:.*?-->", "", last_asst or "", flags=re.S)
        did = re.sub(r"\s+", " ", did).strip()
        lines = [
            "---",
            "name: _last-session",
            "tags: [meta, type/state]",
            f"asserted: {now.strftime('%Y-%m-%d')}",
            "status: active",
            "---",
            "",
            "# Last session — where you left off",
            "",
            f"**{now.strftime('%Y-%m-%d %H:%M')}** · `{ctx}` · overwritten each turn by the "
            "`capture-exchange` Stop hook. ↩ [[_Home]]",
            "",
        ]
        if asked:
            lines += ["**Asked:** " + asked[:400], ""]
        if did:
            lines += ["**Did:** " + did[:500], ""]
        HL.atomic_write(
            os.path.join(HL.MEM, "_infra", "_last-session.md"), "\n".join(lines) + "\n"
        )
    except Exception as e:
        HL.log_err("capture-exchange.last-session", e)


def _write_session_note(now, sid, proj, branch, entry, links):
    """Accumulate a per-session summary note under Sessions/ — a running record of
    everything this session did + a deduped ## Related list of every note it linked.
    Rewritten each turn (small file). Automatic; never relies on the agent remembering."""
    try:
        sdir = os.path.join(HL.MEM, "Sessions")
        os.makedirs(sdir, exist_ok=True)
        sid8 = (re.sub(r"[^A-Za-z0-9]", "", sid or "nosess") or "nosess")[:8]
        day = now.strftime("%Y-%m-%d")
        path = os.path.join(sdir, f"{day}__{sid8}.md")
        log, related = [], []
        if os.path.exists(path):
            txt = open(path, errors="ignore").read()
            log = re.findall(r"^- \*\*\d\d:\d\d\*\* .*$", txt, re.M)
            if "## Related" in txt:
                related = re.findall(r"\[\[([^\]]+)\]\]", txt.split("## Related", 1)[1])
        log.append(f"- **{now.strftime('%H:%M')}** {entry}")
        for l in links:
            if l not in related:
                related.append(l)
        ctx = (proj + (f"@{branch}" if branch else "")) if proj else "(no project)"
        body = (
            [
                "---",
                f"name: session-{day}-{sid8}",
                f'title: "Session {day} — {ctx}"',
                f'description: "Auto session log ({ctx}) — {len(log)} turns; what this session did + links to related notes."',
                "tags: [meta, type/session]",
                f"asserted: {day}",
                "status: active",
                "---",
                "",
                f"# Session {day} — {ctx}",
                "",
                "🟢 auto-generated by the `capture-exchange` Stop hook — running record of everything "
                "this session did. ↩ [[_Home]]",
                "",
                "## What this session did",
            ]
            + log
            + ["", "## Related"]
        )
        body += (
            [f"- [[{l}]]" for l in related] if related else ["- (no linked notes yet)"]
        )
        HL.atomic_write(path, "\n".join(body) + "\n")
    except Exception as e:
        HL.log_err("capture-exchange.session-note", e)


def _git_autocommit(now):
    """Opt-in: commit the vault after each session so it is genuinely git-auditable.
    Enable with SECOND_BRAIN_GIT_AUTOCOMMIT=1. No-op unless the vault is a git repo and
    something changed. Quiet, timeout-bounded, never raises."""
    if not os.environ.get("SECOND_BRAIN_GIT_AUTOCOMMIT"):
        return
    try:
        import subprocess

        if not os.path.isdir(os.path.join(HL.MEM, ".git")):
            return
        st = subprocess.run(
            ["git", "-C", HL.MEM, "status", "--porcelain"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if not st.stdout.strip():
            return
        subprocess.run(
            ["git", "-C", HL.MEM, "add", "-A"], capture_output=True, timeout=15
        )
        subprocess.run(
            [
                "git",
                "-C",
                HL.MEM,
                "commit",
                "-q",
                "-m",
                "second-brain: session capture " + now.strftime("%Y-%m-%d %H:%M"),
            ],
            capture_output=True,
            timeout=15,
        )
    except Exception as e:
        HL.log_err("capture-exchange.autocommit", e)


def main():
    if not HL.vault_ok():
        return
    try:
        hook = json.loads(sys.stdin.read())
    except Exception:
        return
    if hook.get("stop_hook_active"):
        return
    tpath = hook.get("transcript_path")
    if not tpath or not os.path.exists(tpath):
        return
    cwd = hook.get("cwd") or ""
    branch = hook.get("gitBranch") or ""
    proj = os.path.basename(cwd.rstrip("/")) if cwd else ""

    last_user = last_asst = None
    for ln in HL.tail_lines(tpath):  # tail only — not the whole file
        ln = ln.strip()
        if not ln:
            continue
        try:
            o = json.loads(ln)
        except Exception:
            continue
        if o.get("isSidechain"):  # skip subagent turns
            continue
        t = o.get("type")
        msg = o.get("message") or {}
        c = msg.get("content")
        if t == "user":
            if isinstance(c, str) and c.strip():
                last_user = c.strip()
            elif isinstance(c, list):
                txt = " ".join(
                    b.get("text", "")
                    for b in c
                    if isinstance(b, dict) and b.get("type") == "text"
                )
                if txt.strip():
                    last_user = txt.strip()  # real text turn, not a tool_result
        elif t == "assistant" and isinstance(c, list):
            txt = "\n".join(
                b.get("text", "")
                for b in c
                if isinstance(b, dict) and b.get("type") == "text"
            )
            if txt.strip():
                last_asst = txt.strip()

    # redact high-confidence secret token shapes before any raw turn text hits disk
    last_user = HL.scrub_secrets(last_user)
    last_asst = HL.scrub_secrets(last_asst)

    captured_type = None
    m = re.search(r"<!--\s*CAPTURE:\s*(.*?)\s*-->", last_asst or "", re.S)
    if m:
        entry = re.sub(r"\s+", " ", m.group(1)).strip()
        tm = re.search(
            r"\btype:\s*(decision|win|incident|context|research|learning)\b",
            entry,
            re.I,
        )
        if tm:
            captured_type = tm.group(1).lower()
            entry = f"({captured_type}) " + re.sub(
                r"\|\|\s*type:\s*\w+", "", entry
            ).strip(" |")
    elif last_user:
        u = re.sub(r"\s+", " ", last_user).strip()
        entry = "(raw) " + (u[:140] + ("…" if len(u) > 140 else ""))
    else:
        return

    now = datetime.now()
    ddir = os.path.join(HL.MEM, "Daily")
    os.makedirs(ddir, exist_ok=True)
    day = now.strftime("%Y-%m-%d")
    dfile = os.path.join(ddir, day + ".md")
    # exclusive create of the header (no double-header race between concurrent Stops)
    try:
        with open(dfile, "x") as f:
            f.write(
                f"---\nname: {day}\ntags: [journal, meta]\n---\n\n# {day}\n\n"
                f"Auto-captured exchanges (via `capture-exchange` Stop hook). ↩ [[_Home]]\n\n"
            )
    except FileExistsError:
        pass
    ctx = f" [{proj}" + (f"@{branch}" if branch else "") + "]" if proj else ""
    with open(dfile, "a") as f:  # append is atomic for a single small write
        f.write(f"- **{now.strftime('%H:%M')}**{ctx} — {entry}\n")

    # Distilled last-session digest (overwritten each turn) — session-resume.py injects this on
    # next SessionStart so a new chat resumes from where this one left off (claude-mem's
    # compress->reinject idea, done headlessly). Kept cheap: no extra transcript passes.
    _write_last_session(now, proj, branch, last_user, last_asst)

    # Per-session summary note (accumulates all turns + links) — always enforced, automatic.
    links = re.findall(r"\[\[([^\]]+)\]\]", m.group(1)) if m else []
    _write_session_note(now, hook.get("session_id"), proj, branch, entry, links)

    # research/learning → durable promote-queue (safety net so curation is never lost)
    if captured_type in ("research", "learning"):
        q = os.path.join(HL.MEM, "_infra", "_promote-queue.md")
        try:
            os.makedirs(os.path.dirname(q), exist_ok=True)
            try:
                with open(q, "x") as f:
                    f.write(
                        "---\nname: _promote-queue\ntags: [meta, type/index]\n---\n\n"
                        "# Promote queue\n\nResearch/learnings flagged for curation into atomic "
                        "notes. `/second-brain consolidate` sweeps this; check off when a curated note "
                        "exists. \u21a9 [[_Home]]\n\n"
                    )
            except FileExistsError:
                pass
            with open(q, "a") as f:
                f.write(f"- [ ] {day} {now.strftime('%H:%M')}{ctx} — {entry}\n")
        except Exception as e:
            HL.log_err("capture-exchange.queue", e)

    # opt-in (SECOND_BRAIN_GIT_AUTOCOMMIT=1): commit the vault so it's genuinely git-auditable
    _git_autocommit(now)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        HL.log_err("capture-exchange", e)
