#!/usr/bin/env python3
"""Stop hook: append a one-line capture of the finished exchange to today's daily note.
Distilled from a <!--CAPTURE: ...--> footer if present, else a raw fallback from the user msg.
Reads only the TAIL of the (possibly 20MB+) transcript. Never blocks; logs failures."""

import sys, os, json, re
from datetime import datetime

import _hooklib as HL

# Windows consoles default to cp1252, where the status glyphs this script prints raise
# UnicodeEncodeError and abort it mid-run. UTF-8 with replacement can never raise.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def _write_last_session(now, proj, branch, last_user, last_asst):
    """Overwrite _infra/_last-session.md with a distilled resume digest of this exchange."""
    try:
        ctx = (proj + (f"@{branch}" if branch else "")) if proj else "(no project)"
        asked = re.sub(r"\s+", " ", last_user or "").strip()
        did = re.sub(r"<!--\s*CAPTURE:.*?-->", "", last_asst or "", flags=re.S)
        did = re.sub(r"\s+", " ", did).strip()
        lines = [
            "---",
            "name: _last-session",
            "tags: [meta, type/state]",
            f"asserted: {now.strftime('%Y-%m-%d')}",
            "status: active",
            "---",
            "",
            "# Last session — where you left off",
            "",
            f"**{now.strftime('%Y-%m-%d %H:%M')}** · `{ctx}` · overwritten each turn by the "
            "`capture-exchange` Stop hook. ↩ [[_Home]]",
            "",
        ]
        if asked:
            lines += ["**Asked:** " + asked[:400], ""]
        if did:
            lines += ["**Did:** " + did[:500], ""]
        HL.atomic_write(
            os.path.join(HL.MEM, "_infra", "_last-session.md"), "\n".join(lines) + "\n"
        )
    except Exception as e:
        HL.log_err("capture-exchange.last-session", e)


def _sect_items(txt, header):
    """List items under '## <header>' in an existing session note (for cumulative merge)."""
    m = re.search(r"^## " + re.escape(header) + r"\n(.*?)(?=^## |\Z)", txt, re.S | re.M)
    return re.findall(r"^- (?:`([^`]+)`|(.+))$", m.group(1), re.M) if m else []


def _merge(old_pairs, new_items, cap):
    """Ordered-unique union of section items, newest kept, bounded at cap."""
    items = [a or b for a, b in old_pairs]
    for it in new_items:
        if it not in items:
            items.append(it)
    return items[-cap:]


def _write_session_note(now, sid, proj, branch, entry, links, scan=None):
    """Accumulate a per-session summary note under Sessions/ — a running record of
    everything this session did, the notes it linked, and the files/commands/errors it
    touched (from the transcript, so an unfootered turn still leaves a usable record).
    Rewritten each turn (small file). Automatic; never relies on the agent remembering."""
    scan = scan or {}
    try:
        sdir = os.path.join(HL.MEM, "Sessions")
        os.makedirs(sdir, exist_ok=True)
        sid8 = (re.sub(r"[^A-Za-z0-9]", "", sid or "nosess") or "nosess")[:8]
        day = now.strftime("%Y-%m-%d")
        path = os.path.join(sdir, f"{day}__{sid8}.md")
        log, related, txt = [], [], ""
        if os.path.exists(path):
            txt = open(path, errors="ignore").read()
            log = re.findall(r"^- \*\*\d\d:\d\d\*\* .*$", txt, re.M)
            if "## Related" in txt:
                related = re.findall(r"\[\[([^\]]+)\]\]", txt.split("## Related", 1)[1])
        line = f"- **{now.strftime('%H:%M')}** {entry}"
        if not (
            log
            and re.sub(r"^- \*\*\d\d:\d\d\*\*", "", log[-1]).strip()
            == re.sub(r"^- \*\*\d\d:\d\d\*\*", "", line).strip()
        ):
            log.append(line)
        for l in links:
            if l not in related:
                related.append(l)
        files = _merge(_sect_items(txt, "Files touched"), scan.get("files", []), 15)
        commands = _merge(_sect_items(txt, "Commands"), scan.get("commands", []), 8)
        errors = _merge(_sect_items(txt, "Errors seen"), scan.get("errors", []), 6)
        ctx = (proj + (f"@{branch}" if branch else "")) if proj else "(no project)"
        body = [
            "---",
            f"name: session-{day}-{sid8}",
            f'title: "Session {day} — {ctx}"',
            f'description: "Auto session log ({ctx}) — {len(log)} turns; what this session did + links to related notes."',
            "tags: [meta, type/session]",
            f"asserted: {day}",
            "status: active",
            "---",
            "",
            f"# Session {day} — {ctx}",
            "",
            "🟢 auto-generated by the `capture-exchange` Stop hook — running record of everything "
            "this session did. ↩ [[_Home]]",
            "",
            "## What this session did",
        ] + log
        if files:
            body += ["", "## Files touched"] + [f"- `{f}`" for f in files]
        if commands:
            body += ["", "## Commands"] + [f"- `{c}`" for c in commands]
        if errors:
            body += ["", "## Errors seen"] + [f"- {e}" for e in errors]
        body += ["", "## Related"]
        body += (
            [f"- [[{l}]]" for l in related] if related else ["- (no linked notes yet)"]
        )
        HL.atomic_write(path, "\n".join(body) + "\n")
    except Exception as e:
        HL.log_err("capture-exchange.session-note", e)


DEBT = "_infra/_note-debt.md"
DEBT_HDR = (
    "---\nname: _note-debt\ntags: [meta, type/state]\nstatus: active\n---\n\n"
    "# Note debt\n\nSessions that changed code but left no curated note. "
    "`memory-recall` surfaces these until a note lands in the project folder. "
    "↩ [[_Home]]\n\n"
)


def _folder_newest(folder):
    """Newest mtime of any curated note in a project folder (0 if none)."""
    d = os.path.join(HL.MEM, folder)
    newest = 0.0
    for root, _dirs, files in os.walk(d):
        for f in files:
            if f.endswith(".md") and not f.startswith("_MOC-"):
                newest = max(newest, os.path.getmtime(os.path.join(root, f)))
    return newest


def _update_note_debt(now, sid, proj, files):
    """Record/clear note debt. A session that edited files OUTSIDE the vault but wrote
    nothing inside it owes a curated note; the entry clears itself once one appears in
    that folder. Warning only — never blocks, so exploration is not penalised."""
    try:
        path = os.path.join(HL.MEM, DEBT)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        existing = []
        if os.path.exists(path):
            existing = [
                l.rstrip()
                for l in open(path, errors="ignore")
                if l.startswith("- [ ] ")
            ]
        # drop entries whose project gained a note after the recorded baseline
        kept = []
        for line in existing:
            m = re.search(r"\[([^\]]+)\] .*baseline (\d+)", line)
            if m and _folder_newest(m.group(1)) > float(m.group(2)):
                continue  # debt paid
            kept.append(line)

        sid8 = (re.sub(r"[^A-Za-z0-9]", "", sid or "nosess") or "nosess")[:8]
        repo_files = [f for f in files if not f.startswith(HL.MEM)]
        vault_files = [f for f in files if f.startswith(HL.MEM)]
        if proj and repo_files and not vault_files:
            if not any(sid8 in l for l in kept):
                kept.append(
                    f"- [ ] {now.strftime('%Y-%m-%d %H:%M')} {sid8} [{proj}] — "
                    f"{len(repo_files)} file(s) changed, no curated note "
                    f"(baseline {int(_folder_newest(proj))})"
                )
        elif vault_files:  # this session wrote notes — clear its own debt
            kept = [l for l in kept if sid8 not in l]

        if kept:
            HL.atomic_write(path, DEBT_HDR + "\n".join(kept) + "\n")
        elif os.path.exists(path):
            HL.atomic_write(path, DEBT_HDR)
    except Exception as e:
        HL.log_err("capture-exchange.note-debt", e)


def _git_autocommit(now):
    """Opt-in: commit the vault after each session so it is genuinely git-auditable.
    Enable with SECOND_BRAIN_GIT_AUTOCOMMIT=1. No-op unless the vault is a git repo and
    something changed. Quiet, timeout-bounded, never raises."""
    if not os.environ.get("SECOND_BRAIN_GIT_AUTOCOMMIT"):
        return
    try:
        import subprocess

        if not os.path.isdir(os.path.join(HL.MEM, ".git")):
            return
        st = subprocess.run(
            ["git", "-C", HL.MEM, "status", "--porcelain"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if not st.stdout.strip():
            return
        subprocess.run(
            ["git", "-C", HL.MEM, "add", "-A"], capture_output=True, timeout=15
        )
        subprocess.run(
            [
                "git",
                "-C",
                HL.MEM,
                "commit",
                "-q",
                "-m",
                "second-brain: session capture " + now.strftime("%Y-%m-%d %H:%M"),
            ],
            capture_output=True,
            timeout=15,
        )
    except Exception as e:
        HL.log_err("capture-exchange.autocommit", e)


def main():
    if not HL.vault_ok():
        return
    try:
        hook = json.loads(sys.stdin.read())
    except Exception:
        return
    if hook.get("stop_hook_active"):
        return
    tpath = hook.get("transcript_path")
    if not tpath or not os.path.exists(tpath):
        return
    cwd = hook.get("cwd") or ""
    branch = hook.get("gitBranch") or ""
    # Route to the vault folder, not the raw cwd basename: a subdir like <repo>/web must
    # tag [<repo>], and an unknown repo registers itself (folder + _MOC hub + config
    # entry) so no note can land in the vault root.
    proj, _proj_is_new = HL.route_project(cwd)
    proj = proj or ""

    # 1MB tail + the shared parser: keeps the last genuine user/assistant pair even when
    # a large tool result sits between them, filters harness-injected "user" messages,
    # and extracts files/commands/errors for the session note.
    scan = HL.scan_transcript(tpath, max_bytes=1_048_576)
    # redact high-confidence secret token shapes before any raw turn text hits disk
    last_user = HL.scrub_secrets(scan["last_user"])
    last_asst = HL.scrub_secrets(scan["last_asst"])

    captured_type = None
    m = re.search(r"<!--\s*CAPTURE:\s*(.*?)\s*-->", last_asst or "", re.S)
    if m:
        entry = re.sub(r"\s+", " ", m.group(1)).strip()
        tm = re.search(
            r"\btype:\s*(decision|win|incident|context|research|learning)\b",
            entry,
            re.I,
        )
        if tm:
            captured_type = tm.group(1).lower()
            entry = f"({captured_type}) " + re.sub(
                r"\|\|\s*type:\s*\w+", "", entry
            ).strip(" |")
        # tags/links stay in the footer for parsing; the Daily line keeps only the summary
        entry = re.sub(r"\s*\|\|\s*(tags|links):.*$", "", entry).strip(" |")
    elif last_user:
        u = re.sub(r"\s+", " ", last_user).strip()
        entry = "(raw) " + (u[:140] + ("…" if len(u) > 140 else ""))
    else:
        return

    now = datetime.now()
    ddir = os.path.join(HL.MEM, "Daily")
    os.makedirs(ddir, exist_ok=True)
    day = now.strftime("%Y-%m-%d")
    dfile = os.path.join(ddir, day + ".md")
    # exclusive create of the header (no double-header race between concurrent Stops)
    try:
        with open(dfile, "x") as f:
            f.write(
                f"---\nname: {day}\ntags: [journal, meta]\n---\n\n# {day}\n\n"
                f"Auto-captured exchanges (via `capture-exchange` Stop hook). ↩ [[_Home]]\n\n"
            )
    except FileExistsError:
        pass
    ctx = f" [{proj}" + (f"@{branch}" if branch else "") + "]" if proj else ""
    # dedupe: a re-fired Stop (or an unchanged footer) must not append the same entry
    # twice. This skips only the Daily append — the session note, digest and note-debt
    # bookkeeping below must still run, or a repeated turn would silently drop all of it.
    dup = False
    try:
        prev = [l for l in open(dfile, errors="ignore") if l.startswith("- **")]
        dup = bool(prev) and re.sub(r"^- \*\*\d\d:\d\d\*\*", "", prev[-1]).strip() == (
            f"{ctx} — {entry}".strip()
        )
    except Exception:
        pass
    if not dup:
        with open(dfile, "a") as f:  # append is atomic for a single small write
            f.write(f"- **{now.strftime('%H:%M')}**{ctx} — {entry}\n")

    # Distilled last-session digest (overwritten each turn) — session-resume.py injects this on
    # next SessionStart so a new chat resumes from where this one left off (claude-mem's
    # compress->reinject idea, done headlessly). Kept cheap: no extra transcript passes.
    _write_last_session(now, proj, branch, last_user, last_asst)

    # Per-session summary note (accumulates all turns + links + files/commands/errors) —
    # always enforced, automatic; unfootered turns still leave a reference-able record.
    links = re.findall(r"\[\[([^\]]+)\]\]", m.group(1)) if m else []
    _write_session_note(now, hook.get("session_id"), proj, branch, entry, links, scan)

    # Curated-note accountability: code changed but no vault write → record the debt.
    _update_note_debt(now, hook.get("session_id"), proj, scan.get("files", []))

    # research/learning → durable promote-queue (safety net so curation is never lost)
    if captured_type in ("research", "learning"):
        q = os.path.join(HL.MEM, "_infra", "_promote-queue.md")
        try:
            os.makedirs(os.path.dirname(q), exist_ok=True)
            try:
                with open(q, "x") as f:
                    f.write(
                        "---\nname: _promote-queue\ntags: [meta, type/index]\n---\n\n"
                        "# Promote queue\n\nResearch/learnings flagged for curation into atomic "
                        "notes. `/second-brain consolidate` sweeps this; check off when a curated note "
                        "exists. \u21a9 [[_Home]]\n\n"
                    )
            except FileExistsError:
                pass
            with open(q, "a") as f:
                f.write(f"- [ ] {day} {now.strftime('%H:%M')}{ctx} — {entry}\n")
        except Exception as e:
            HL.log_err("capture-exchange.queue", e)

    # opt-in (SECOND_BRAIN_GIT_AUTOCOMMIT=1): commit the vault so it's genuinely git-auditable
    _git_autocommit(now)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        HL.log_err("capture-exchange", e)
